---
language: python

python:
  - "3.7"

services:
  - docker

env:
  matrix:
    - distribution="alpine:latest"
    - distribution="alpine:edge"
    - distribution="robertdebock/docker-centos-systemd:7"
    - distribution="robertdebock/docker-centos-systemd:latest"
    - distribution="robertdebock/docker-debian-systemd:latest"
    - distribution="robertdebock/docker-debian-systemd:stable"
    - distribution="robertdebock/docker-debian-systemd:unstable"
    - distribution="robertdebock/docker-fedora-systemd:latest"
    - distribution="robertdebock/docker-fedora-systemd:rawhide"
    - distribution="opensuse/leap"
    - distribution="robertdebock/docker-ubuntu-systemd:latest"
    - distribution="robertdebock/docker-ubuntu-systemd:devel"
    - distribution="robertdebock/docker-ubuntu-systemd:rolling"

matrix:
  allow_failures:
    - env: distribution="alpine:edge"
    - env: distribution="robertdebock/docker-debian-systemd:unstable"
    - env: distribution="robertdebock/docker-fedora-systemd:rawhide"
    - env: distribution="robertdebock/docker-ubuntu-systemd:devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install molecule
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "CnZNemWKT3dCbTLJjuMLcrpNADsTEhOD//yrNRE6unXdTnzYL/z+FwSKmGZnW8wREC/tfLuctiyfemcB+c7cCq50ju6MCE07yHyrAOv1WY7Y6JHMSGxus5YeoaQ/JwQFjbRaec/K8B0o5s7tF4D87zrliBOHQMGYBeUpqkOQDmdRivi0SbtWHRZtHq1IsBdICQ9yJmBvPX2gVNBiESWz2PBA3lScge4f+K2gKBbPZzLQzn9K3St28Rhg99Av7zVsfFEITDyo4rj6AIgeuuZ3Cn6BqhFAlnBMzInvQjAgATtWAbfY9D2+qnZ/NZ164cwk6OnQuAZyHvvcM0l9uOLGsBgMtPjF0tUry857UcTqSYUZk7e2P2+MwDJcSW71BbKA+pw1Lad7ZDEZxkfEObm6EuXeJji7LVjDvYWb7AvNBpqt8baHQ8Lklv992RnakX7tBwmTGvhlAsWj8EArqXlR/0fVRHMAxBIZTCQrrCTF51oF660ORGe2ZT8q9HYDL1jWF0Nc3lAwqEfySt2cEmbpaWWOqgewY6AeP2yVHYPUjBPXpPx0tb6/RyFHZGFnRXhbCuy8IlS7kHDllvz2isAe4f6s58iue1TxmvR1AhS3xYYHl+Ja7FvMoE+7E9R3lVsPWyF6hkvBm4OF7OTCTDiPyvvLIQK4f0jdgPnrYtenhv4="
  email: false
